#!/usr/bin/env python3
"""Refresh snapshot.js (the fallback data baked into the site) from the xlsx.

    pip3 install openpyxl
    python3 make_snapshot.py "path/to/Mahjong Tracker with Elo.xlsx"

Optional: the site reads your live Google Sheet once config.js has a URL.
The snapshot is only what shows if the sheet can't be reached.
Reads the Log sheet (one row per player per game, columns A-D).
"""
import json
import sys
from datetime import datetime, date
from pathlib import Path

import openpyxl

HERE = Path(__file__).parent


def read_games(xlsx):
    wb = openpyxl.load_workbook(xlsx, data_only=True)
    games, order, problems = {}, [], []
    for row in wb["Log"].iter_rows(min_row=2):
        when, gid, name, result = (c.value for c in row[:4])
        if not gid:
            continue
        gid, name, result = str(gid).strip(), str(name).strip(), str(result).strip()
        if result not in ("Win", "Loss"):
            problems.append(f"{gid}: unexpected result '{result}' for {name}")
        if gid not in games:
            if isinstance(when, (datetime, date)):
                when = when.strftime("%Y-%m-%d")
            games[gid] = {"id": gid, "date": str(when), "players": [], "winners": []}
            order.append(gid)
        games[gid]["players"].append(name)
        if result == "Win":
            games[gid]["winners"].append(name)
    for gid in order:
        if len(games[gid]["winners"]) != 1:
            problems.append(f"{gid}: {len(games[gid]['winners'])} winners (expected 1)")
    ordered = [games[g] for g in order]
    try:  # order by Game ID number, like the site does
        ordered.sort(key=lambda g: int("".join(ch for ch in g["id"] if ch.isdigit())))
    except ValueError:
        pass
    return ordered, problems


def main():
    xlsx = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.home() / "Downloads" / "Mahjong Tracker with Elo (1).xlsx"
    games, problems = read_games(xlsx)
    for p in problems:
        print("WARNING:", p)
    (HERE / "snapshot.js").write_text(
        "// Generated by make_snapshot.py - fallback data only.\n"
        "window.MAHJONG_SNAPSHOT = " + json.dumps({"games": games}, ensure_ascii=False) + ";\n"
    )
    print(f"{len(games)} games -> snapshot.js")


if __name__ == "__main__":
    main()
